- id: '1765211431652'
  alias: Daily vacuum cleaning routine
  description: ''
  triggers:
  - trigger: time
    at: '12:00:00'
  conditions: []
  actions:
  - action: vacuum.start
    target:
      entity_id: vacuum.roborock_qrevo_master
  mode: single
