- id: '1765211431652'
  alias: Daily vacuum cleaning routine
  description: ''
  triggers:
  - trigger: time_pattern
    hours: '12'
  conditions: []
  actions:
  - device_id: e52a4e38f8d6fb19ddd4b95fba2f5a59
    domain: vacuum
    entity_id: d7c379f3658c7dc829a6139fa2b831e3
    type: clean
    metadata:
      secondary: false
  mode: single
