- id: '1765211431652'
  alias: Daily vacuum cleaning routine
  description: ''
  triggers:
  - trigger: time
    at: '12:00:00'
  conditions:
  - alias: Daily vacuuming is enabled
    condition: state
    entity_id: input_boolean.daily_vacuum_enabled
    state: 'on'
  - alias: Run only on weekdays
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  # - alias: Nobody is home
  #   condition: numeric_state
  #   entity_id: zone.home
  #   below: 1
  - alias: Vacuum is docked or idle
    condition: state
    entity_id: vacuum.roborock_qrevo_master
    state:
    - docked
    - idle
  - alias: Vacuum battery is at least 30%
    condition: numeric_state
    entity_id: sensor.roborock_qrevo_master_battery
    above: 29
  actions:
  - action: vacuum.start
    target:
      entity_id: vacuum.roborock_qrevo_master
  mode: single
